#!/bin/bash

clear
printf "\033[1;35mWelcome to >>> PiggyShell! \n\
\t\t    _/\_/) \n\
\t\t   (),x  ( \n\
\t   /\______///   \( \n\
\t _/~       (/\    )' \n\
\t[_,        )=\   / \n\
\t  \ )_____(( (( / \n\
\t   |||   /// /// \n\
\t    ~    ~~  ~~ \n\
"