#!/bin/bash

for ((i=0;i<9999999999;i++)); do
	clear
   printf "\033[1;35m \n\
\t\t    _/\_/) \n\
\t\t   (),~  ( \n\
\t   /\______///   \( \n\
\t _/x       (/\    )' \n\
\t[_,        )==\  / \n\
\t  \ )_____(( (( / \n\
\t   |||   /// /// \n\
\t    ~    ~~  ~~ \n\
"
   sleep 0.1
   clear
   printf "\033[1;35mWelcome to >>> PiggyShell! \n\
\t\t    _/\_/) \n\
\t\t   (),~  ( \n\
\t   /\______///   \( \n\
\t _/x       (/\    )' \n\
\t[_,        )=\   / \n\
\t  \ )_____(( (( / \n\
\t   |||   /// /// \n\
\t    ~    ~~  ~~ \n\
"
   sleep 0.1
done

